
version: '3'
services:
    server:
        build:
            context: ./
            dockerfile: ./Dockerfile
        command: bash -c "python ./manage.py makemigrations --noinput && python ./manage.py migrate --noinput && gunicorn config.wsgi -c ./config/gunicorn.py"
        volumes:
            - ./:/server
        ports:
            - 8000:8000
        depends_on:
            - db
            - redis
        environment:
            DEBUG: 'True'
            DATABASE_URL: 'postgres://postgres:@db:5432/postgres'
            BROKER_URL: 'amqp://user:password@rabbitmq:5672/my_vhost'

    db:
        image: postgres:11.2
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
    redis:
        image: redis:latest
        expose:
            - "6379"